using System;using System.IO;using System.Linq;using System.Runtime.InteropServices;using System.Security.Principal;using System.Text;using System.Threading.Tasks;using System.Windows;using System.Windows.Input;using System.Windows.Interop;using System.Windows.Media;using System.Windows.Media.Imaging;using Microsoft.Win32;using AnvilDepth.Services;
namespace AnvilDepth{
public partial class MainWindow:Window{
string? curPath;float[]? curDepth;byte[]? curBgra;int dW,dH;DepthEngine? eng;
[DllImport("shell32.dll")]static extern void DragAcceptFiles(IntPtr h,bool f);
[DllImport("shell32.dll")]static extern uint DragQueryFile(IntPtr h,uint i,StringBuilder b,uint c);
[DllImport("shell32.dll")]static extern void DragFinish(IntPtr h);
const int WM_DROP=0x0233;
public MainWindow(){InitializeComponent();Loaded+=OnLoaded;SourceInitialized+=(s,e)=>{try{var hwnd=new WindowInteropHelper(this).Handle;var src=HwndSource.FromHwnd(hwnd);src?.AddHook(WndProc);DragAcceptFiles(hwnd,true);}catch{}};}
IntPtr WndProc(IntPtr h,int m,IntPtr w,IntPtr l,ref bool hd){if(m==WM_DROP){try{uint c=DragQueryFile(w,0xFFFFFFFF,null,0);if(c>0){var sb=new StringBuilder(1024);DragQueryFile(w,0,sb,(uint)sb.Capacity);Dispatcher.Invoke(()=>Load(sb.ToString()));}DragFinish(w);hd=true;}catch{}}return IntPtr.Zero;}
async void OnLoaded(object s,RoutedEventArgs e){try{bool admin=new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator);if(admin) DragDebugText.Text="Admin - drag blocked!";}catch{}GpuStatusText.Text="Ready V7.20 Checklist";eng=new DepthEngine();var st=await eng.InitializeAsync();GpuStatusText.Text=st;AiModelCheck.IsChecked=false;UseLabCheck.IsChecked=true;PercentileCheck.IsChecked=true;}
bool DragOk(DragEventArgs e){if(e.Data.GetDataPresent(DataFormats.FileDrop)){var f=e.Data.GetData(DataFormats.FileDrop) as string[];if(f!=null&&f.Length>0){string ext=Path.GetExtension(f[0]).ToLower();if(new[]{".png",".jpg",".jpeg",".bmp",".tiff",".tga",".webp"}.Contains(ext)){e.Effects=DragDropEffects.Copy;e.Handled=true;DragDebugText.Text=$"Hover {Path.GetFileName(f[0])}";return true;}}}e.Effects=DragDropEffects.None;e.Handled=true;return false;}
void Window_DragEnter(object s,DragEventArgs e){DragOk(e);}void Window_DragOver(object s,DragEventArgs e){DragOk(e);}
void Window_Drop(object s,DragEventArgs e){try{if(e.Data.GetData(DataFormats.FileDrop) is string[] f&&f.Length>0) Load(f[0]);}catch(Exception ex){MessageBox.Show(ex.Message);}e.Handled=true;}
void DropZone_DragEnter(object s,DragEventArgs e){DragOk(e);}void DropZone_DragOver(object s,DragEventArgs e){DragOk(e);}
void DropZone_Drop(object s,DragEventArgs e){try{if(e.Data.GetData(DataFormats.FileDrop) is string[] f&&f.Length>0) Load(f[0]);}catch(Exception ex){MessageBox.Show(ex.Message);}e.Handled=true;}
void DropZone_MouseDown(object s,MouseButtonEventArgs e){var d=new OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg;*.bmp;*.tiff;*.tga;*.webp"};if(d.ShowDialog()==true) Load(d.FileName);}
void Load(string path){try{curPath=path;var bmp=new BitmapImage(new Uri(path));InputPreview.Source=bmp;InputPreview.Visibility=Visibility.Visible;DropText.Visibility=Visibility.Collapsed;var wb=new WriteableBitmap(bmp);wb=new WriteableBitmap(new FormatConvertedBitmap(wb,PixelFormats.Bgra32,null,0));int st=wb.PixelWidth*4;byte[] pix=new byte[wb.PixelHeight*st];wb.CopyPixels(pix,st,0);curBgra=pix;dW=wb.PixelWidth;dH=wb.PixelHeight;GenerateBtn.IsEnabled=true;GpuStatusText.Text=$"{Path.GetFileName(path)} {dW}x{dH}";if(AiModelCheck.IsChecked==false) Reproc();}catch(Exception ex){MessageBox.Show(ex.Message);}}
async void Generate_Click(object s,RoutedEventArgs e){
float fl=(float)FlattenSlider.Value,flR=(float)FlattenRadiusSlider.Value,lowF=(float)LowFreqSlider.Value,midF=(float)MidFreqSlider.Value,highF=(float)HighFreqSlider.Value,det=(float)DetailSlider.Value,gam=(float)GammaSlider.Value,str=(float)StrengthSlider.Value,hi=(float)HighlightsSlider.Value,mid=(float)MidtonesSlider.Value,sh=(float)ShadowsSlider.Value;bool inv=InvertCheck.IsChecked==true,rem=RemoveBgCheck.IsChecked==true,hq=HighQualityCheck.IsChecked==true,ai=AiModelCheck.IsChecked==true,lab=UseLabCheck.IsChecked==true,seam=SeamlessCheck.IsChecked==true;float seamB=(float)SeamBlendSlider.Value;bool zeroMid=ZeroMidGrayCheck.IsChecked==true;float zeroL=(float)ZeroLevelSlider.Value+(zeroMid?0.5f:0f);bool perc=PercentileCheck.IsChecked==true;
var bgra=curBgra;int w=dW,h=dH;string? p=curPath;
try{
if(p==null) return;
if(!ai){if(bgra==null) return;GenerateBtn.Content="PROCESSING...";GenerateBtn.IsEnabled=false;float[] proc=null!;await Task.Run(()=>{proc=ImageProcessor.ProcessTextureAtlasAdvanced(bgra!,w,h,det,gam,inv,hi,mid,sh,rem,lab,fl,flR,lowF,midF,highF,seam,seamB,zeroMid,zeroL,perc,0.02f,0.98f);});curDepth=proc;OutputImage.Source=ImageProcessor.FloatArrayToBitmapSource(proc,w,h);GenerateBtn.Content="DONE";GenerateBtn.IsEnabled=true;SavePngBtn.IsEnabled=true;SaveExrBtn.IsEnabled=true;SaveTiffBtn.IsEnabled=true;SaveStlBtn.IsEnabled=true;return;}
GenerateBtn.Content="GENERATING...";GenerateBtn.IsEnabled=false;
var res=await eng!.EstimateDepthAsync(p!,hq);
var proc2=ImageProcessor.ProcessForSculptOKQuality(res.Depth,res.Width,res.Height,bgra,str,det,lowF,midF,highF,gam,inv,hi,mid,sh,zeroMid,zeroL);
curDepth=proc2;dW=res.Width;dH=res.Height;OutputImage.Source=ImageProcessor.FloatArrayToBitmapSource(proc2,dW,dH);
GenerateBtn.Content="DONE";GenerateBtn.IsEnabled=true;SavePngBtn.IsEnabled=true;SaveExrBtn.IsEnabled=true;SaveTiffBtn.IsEnabled=true;SaveStlBtn.IsEnabled=true;
}catch(Exception ex){MessageBox.Show(ex.Message);GenerateBtn.Content="FAILED";GenerateBtn.IsEnabled=true;}}
void Mode_Changed(object s,RoutedEventArgs? e){if(AiModelCheck==null) return;GenerateBtn.Content=AiModelCheck.IsChecked==true?"AI DEPTH":"RELIEF";}
void Reproc(){try{if(AiModelCheck.IsChecked==true) return;if(curBgra==null) return;float fl=(float)FlattenSlider.Value,flR=(float)FlattenRadiusSlider.Value,lowF=(float)LowFreqSlider.Value,midF=(float)MidFreqSlider.Value,highF=(float)HighFreqSlider.Value,det=(float)DetailSlider.Value,gam=(float)GammaSlider.Value,hi=(float)HighlightsSlider.Value,mid=(float)MidtonesSlider.Value,sh=(float)ShadowsSlider.Value;bool inv=InvertCheck.IsChecked==true,rem=RemoveBgCheck.IsChecked==true,lab=UseLabCheck.IsChecked==true,seam=SeamlessCheck.IsChecked==true;float seamB=(float)SeamBlendSlider.Value;bool zeroMid=ZeroMidGrayCheck.IsChecked==true;float zeroL=(float)ZeroLevelSlider.Value+(zeroMid?0.5f:0f);bool perc=PercentileCheck.IsChecked==true;var proc=ImageProcessor.ProcessTextureAtlasAdvanced(curBgra!,dW,dH,det,gam,inv,hi,mid,sh,rem,lab,fl,flR,lowF,midF,highF,seam,seamB,zeroMid,zeroL,perc,0.02f,0.98f);curDepth=proc;OutputImage.Source=ImageProcessor.FloatArrayToBitmapSource(proc,dW,dH);}catch{}}
void Slider_ValueChanged(object s,RoutedPropertyChangedEventArgs<double> e){if(StrengthLabel!=null) StrengthLabel.Text=StrengthSlider.Value.ToString("0.0");if(DetailLabel!=null) DetailLabel.Text=DetailSlider.Value.ToString("0.00");if(GammaLabel!=null) GammaLabel.Text=GammaSlider.Value.ToString("0.00");if(ShadowsLabel!=null) ShadowsLabel.Text=ShadowsSlider.Value.ToString("0.00");if(MidtonesLabel!=null) MidtonesLabel.Text=MidtonesSlider.Value.ToString("0.00");if(HighlightsLabel!=null) HighlightsLabel.Text=HighlightsSlider.Value.ToString("0.00");if(FlattenLabel!=null) FlattenLabel.Text=FlattenSlider.Value.ToString("0.00");if(FlattenRadiusLabel!=null) FlattenRadiusLabel.Text=FlattenRadiusSlider.Value.ToString("0");if(LowFreqLabel!=null) LowFreqLabel.Text=LowFreqSlider.Value.ToString("0.00");if(MidFreqLabel!=null) MidFreqLabel.Text=MidFreqSlider.Value.ToString("0.00");if(HighFreqLabel!=null) HighFreqLabel.Text=HighFreqSlider.Value.ToString("0.00");if(SeamBlendLabel!=null) SeamBlendLabel.Text=SeamBlendSlider.Value.ToString("0.00");if(ZeroLevelLabel!=null) ZeroLevelLabel.Text=ZeroLevelSlider.Value.ToString("0.00");if(AiModelCheck!=null&&AiModelCheck.IsChecked==false&&curBgra!=null) Reproc();}
void SavePng_Click(object s,RoutedEventArgs e){if(curDepth==null) return;var d=new SaveFileDialog{Filter="PNG 16-bit|*.png",FileName="depth_16bit.png"};if(d.ShowDialog()==true) ImageProcessor.SaveAs16Bit(curDepth,dW,dH,d.FileName);}
void SaveExr_Click(object s,RoutedEventArgs e){if(curDepth==null) return;var d=new SaveFileDialog{Filter="EXR|*.exr",FileName="depth_32bit.exr"};if(d.ShowDialog()==true) ImageProcessor.SaveAsEXR(curDepth,dW,dH,d.FileName);}
void SaveTiffBtn_Click(object s,RoutedEventArgs e){if(curDepth==null) return;var d=new SaveFileDialog{Filter="TIFF|*.tiff",FileName="depth_32bit.tiff"};if(d.ShowDialog()==true) ImageProcessor.SaveAsTiff32(curDepth,dW,dH,d.FileName);}
void SaveStl_Click(object s,RoutedEventArgs e){if(curDepth==null) return;var d=new SaveFileDialog{Filter="STL|*.stl",FileName="relief.stl"};if(d.ShowDialog()==true) StlExporter.SaveAsStl(curDepth,dW,dH,d.FileName,10f);}
}
}
