using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace AnvilDepth.Services;

/// <summary>
/// Converts a depth/height map into 3D mesh formats — binary STL (geometry only, for 3D
/// printing/sculpting) and Wavefront OBJ (geometry + vertex normals + UVs, for game engines
/// and DCC tools that need more than raw triangles). Full-resolution textures (e.g. 2048x2048)
/// would produce tens of millions of triangles, so the grid is downsampled to a manageable cap.
///
/// BuildHeightGrid is also used by MainWindow's live 3D preview, so the preview, the STL, and
/// the OBJ are all built from the same sampled grid — what you see in the viewport is what
/// gets exported, not a separately-approximated preview.
/// </summary>
public static class StlExporter
{
    private const int MaxGridSize = 256;

    /// <summary>Downsamples a depth map to a grid no larger than MaxGridSize per axis (large
    /// source textures would otherwise produce an unusably huge mesh). Returns heights indexed
    /// [gx, gy], each in the source map's original 0..1 range (not yet scaled).</summary>
    public static float[,] BuildHeightGrid(float[] depth, int width, int height, out int gridW, out int gridH)
    {
        gridW = Math.Min(width, MaxGridSize);
        gridH = Math.Min(height, MaxGridSize);

        var heights = new float[gridW, gridH];
        for (int gy = 0; gy < gridH; gy++)
        {
            int sy = (int)((long)gy * (height - 1) / Math.Max(1, gridH - 1));
            for (int gx = 0; gx < gridW; gx++)
            {
                int sx = (int)((long)gx * (width - 1) / Math.Max(1, gridW - 1));
                heights[gx, gy] = depth[sy * width + sx];
            }
        }
        return heights;
    }

    public static void SaveAsStl(float[] depth, int width, int height, string path, float heightScale)
    {
        var heights = BuildHeightGrid(depth, width, height, out int gridW, out int gridH);
        var triangles = new List<(Vec3 a, Vec3 b, Vec3 c)>();

        for (int gy = 0; gy < gridH - 1; gy++)
        {
            for (int gx = 0; gx < gridW - 1; gx++)
            {
                var p00 = new Vec3(gx, gy, heights[gx, gy] * heightScale);
                var p10 = new Vec3(gx + 1, gy, heights[gx + 1, gy] * heightScale);
                var p01 = new Vec3(gx, gy + 1, heights[gx, gy + 1] * heightScale);
                var p11 = new Vec3(gx + 1, gy + 1, heights[gx + 1, gy + 1] * heightScale);

                triangles.Add((p00, p10, p11));
                triangles.Add((p00, p11, p01));
            }
        }

        WriteBinaryStl(path, triangles);
    }

    /// <summary>Wavefront OBJ export: same grid/geometry as SaveAsStl, plus per-vertex normals
    /// (averaged from adjacent face normals) and 0..1 UVs — so the mesh can carry the normal map
    /// generated by ImageProcessor.ComputeNormalMap into a game engine or DCC tool, unlike STL
    /// which is geometry-only.</summary>
    public static void SaveAsObj(float[] depth, int width, int height, string path, float heightScale)
    {
        var heights = BuildHeightGrid(depth, width, height, out int gridW, out int gridH);

        var positions = new Vec3[gridW, gridH];
        var normalAccum = new Vec3[gridW, gridH];
        for (int gy = 0; gy < gridH; gy++)
            for (int gx = 0; gx < gridW; gx++)
                positions[gx, gy] = new Vec3(gx, gy, heights[gx, gy] * heightScale);

        var faces = new List<(int ax, int ay, int bx, int by, int cx, int cy)>();
        for (int gy = 0; gy < gridH - 1; gy++)
        {
            for (int gx = 0; gx < gridW - 1; gx++)
            {
                AddFace(gx, gy, gx + 1, gy, gx + 1, gy + 1);
                AddFace(gx, gy, gx + 1, gy + 1, gx, gy + 1);

                void AddFace(int ax, int ay, int bx, int by, int cx, int cy)
                {
                    var n = Normal(positions[ax, ay], positions[bx, by], positions[cx, cy]);
                    normalAccum[ax, ay] = Add(normalAccum[ax, ay], n);
                    normalAccum[bx, by] = Add(normalAccum[bx, by], n);
                    normalAccum[cx, cy] = Add(normalAccum[cx, cy], n);
                    faces.Add((ax, ay, bx, by, cx, cy));
                }
            }
        }

        using var sw = new StreamWriter(path, false, Encoding.ASCII);
        sw.WriteLine("# AnvilDepth OBJ export");
        var ci = CultureInfo.InvariantCulture;

        // Vertices, normals, UVs — OBJ indices are 1-based.
        for (int gy = 0; gy < gridH; gy++)
        {
            for (int gx = 0; gx < gridW; gx++)
            {
                var p = positions[gx, gy];
                sw.WriteLine(string.Create(ci, $"v {p.X} {p.Y} {p.Z}"));
            }
        }
        for (int gy = 0; gy < gridH; gy++)
        {
            for (int gx = 0; gx < gridW; gx++)
            {
                var n = NormalizeOrUp(normalAccum[gx, gy]);
                sw.WriteLine(string.Create(ci, $"vn {n.X} {n.Y} {n.Z}"));
            }
        }
        for (int gy = 0; gy < gridH; gy++)
        {
            for (int gx = 0; gx < gridW; gx++)
            {
                float u = gridW > 1 ? gx / (float)(gridW - 1) : 0f;
                float v = gridH > 1 ? 1f - gy / (float)(gridH - 1) : 0f; // flip V — image-space Y grows downward, UV-space grows upward
                sw.WriteLine(string.Create(ci, $"vt {u} {v}"));
            }
        }

        int Index(int gx, int gy) => gy * gridW + gx + 1;
        foreach (var (ax, ay, bx, by, cx, cy) in faces)
        {
            int ia = Index(ax, ay), ib = Index(bx, by), ic = Index(cx, cy);
            sw.WriteLine($"f {ia}/{ia}/{ia} {ib}/{ib}/{ib} {ic}/{ic}/{ic}");
        }
    }

    private static void WriteBinaryStl(string path, List<(Vec3 a, Vec3 b, Vec3 c)> triangles)
    {
        using var fs = new FileStream(path, FileMode.Create, FileAccess.Write);
        using var bw = new BinaryWriter(fs, Encoding.ASCII);

        var header = new byte[80];
        Encoding.ASCII.GetBytes("AnvilDepth STL export".PadRight(80)[..80]).CopyTo(header, 0);
        bw.Write(header);
        bw.Write((uint)triangles.Count);

        foreach (var (a, b, c) in triangles)
        {
            var normal = Normal(a, b, c);
            bw.Write(normal.X); bw.Write(normal.Y); bw.Write(normal.Z);
            bw.Write(a.X); bw.Write(a.Y); bw.Write(a.Z);
            bw.Write(b.X); bw.Write(b.Y); bw.Write(b.Z);
            bw.Write(c.X); bw.Write(c.Y); bw.Write(c.Z);
            bw.Write((ushort)0);
        }
    }

    private static Vec3 Normal(Vec3 a, Vec3 b, Vec3 c)
    {
        var u = new Vec3(b.X - a.X, b.Y - a.Y, b.Z - a.Z);
        var v = new Vec3(c.X - a.X, c.Y - a.Y, c.Z - a.Z);
        var n = new Vec3(
            u.Y * v.Z - u.Z * v.Y,
            u.Z * v.X - u.X * v.Z,
            u.X * v.Y - u.Y * v.X);
        float len = MathF.Sqrt(n.X * n.X + n.Y * n.Y + n.Z * n.Z);
        return len > 1e-8f ? new Vec3(n.X / len, n.Y / len, n.Z / len) : new Vec3(0, 0, 1);
    }

    private static Vec3 Add(Vec3 a, Vec3 b) => new Vec3(a.X + b.X, a.Y + b.Y, a.Z + b.Z);

    private static Vec3 NormalizeOrUp(Vec3 n)
    {
        float len = MathF.Sqrt(n.X * n.X + n.Y * n.Y + n.Z * n.Z);
        return len > 1e-8f ? new Vec3(n.X / len, n.Y / len, n.Z / len) : new Vec3(0, 0, 1);
    }

    internal readonly struct Vec3
    {
        public readonly float X, Y, Z;
        public Vec3(float x, float y, float z) { X = x; Y = y; Z = z; }
    }
}
